name: Publish .deb to GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev

      - uses: actions/setup-go@v5 # Sets up the Go environment
        with:
          go-version: '1.24.6'

      - name: Build
        run: go build -o icrn

      - name: Build .deb package
        run: ./build-deb.sh

      - id: deb
        run: |
          deb_file=$(find . -name "*.deb" | head -n 1)
          echo "deb_file=$deb_file" >> $GITHUB_OUTPUT
      - name: Create Release

        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.deb.outputs.deb_file }}
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
